services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compoundDB
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 3306:3306
  
  Task-Backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./Task-Backend/:/app
      - /app/node_modules
    environment:
      - PORT=3000

      
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npm install && npm run dev:db"
  
  Task-Frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./Task-Frontend/:/app
      - /app/node_modules
    command: sh -c "npm install --lrgacy-peer-deps && npm start -- --host=0.0.0.0"
    ports:
      - 4200:4200
    depends_on:
      - Task-Backend